name: linux-build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure (CMake)
        working-directory: quant_enterprise_strategy
        run: cmake -S src -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: quant_enterprise_strategy
        run: cmake --build build -j$(nproc)

      - name: List build outputs
        run: |
          ls -la quant_enterprise_strategy/src/bin || true

